### ISSUE TITLE
embedding模型能用ollama部署的吗？试了试没成功

### ISSUE THREAD

**Issue by martinzhang777** [win4r/GraphRAG4OpenWebUI#5]
尝试修改这个为ollama部署的embedding模型，报错
# 设置嵌入API基础URL（默认为OpenAI的API）
export API_BASE_EMBEDDING="http://localhost:11434/v1"

# 设置嵌入模型（默认为"text-embedding-3-small"）
export GRAPHRAG_EMBEDDING_MODEL="znbang/bge:large-zh-v1.5-f32"

**Comment by MrCui** [comment]
GraphRAG框架的问题,   他们 Issues 里有人报这个问题,  用LLama,cpp 吧.    MS昨天应该修复这个问题了.   可能源还没更新吧.

**Comment by martinzhang777** [comment]
> GraphRAG框架的问题, 他们 Issues 里有人报这个问题, 用LLama,cpp 吧. MS昨天应该修复这个问题了. 可能源还没更新吧.

好的，感谢
