### ISSUE TITLE
全局搜索出错，json.loads(search_response)["points"]找不到key points

### ISSUE THREAD

**Issue by xldistance** [win4r/GraphRAG4OpenWebUI#9]
graphrag的global_search/serach.py里面的函数parse_search_response，parsed_elements = json.loads(search_response)["points"]这里运行出错

**Comment by xldistance** [comment]
global_search/serach.py里面修改如下，不知道对不对
```
    def parse_search_response(self, search_response: str) -> list[dict[str, Any]]:
        """Parse the search response json and return a list of key points.

        Parameters
        ----------
        search_response: str
            The search response json string

        Returns
        -------
        list[dict[str, Any]]
            A list of key points, each key point is a dictionary with "answer" and "score" keys
        """
        parsed_elements = json.loads(search_response)
        points = parsed_elements.get("points",None)
        if points:
            return [
                {
                    "answer": element["description"],
                    "score": int(element["score"]),
                }
                for element in parsed_elements
            ]
        else:
            if "content" in parsed_elements:
                return [
                    {
                        "answer":parsed_elements["content"],
                        "score":1
                    }
                ]
```

**Comment by shaoqing404** [comment]
> global_search/serach.py里面的函数parse_search_response，parsed_elements = json.loads(search_response)["points"]这里运行出错

修改setup_search_engines 下global_search_engine = GlobalSearch(
        llm=llm,
        context_builder=global_context_builder,
        token_encoder=token_encoder,
        max_data_tokens=12000,
        map_llm_params=map_llm_params,
        reduce_llm_params=reduce_llm_params,
        allow_general_knowledge=False,
        json_mode=True,
        context_builder_params=global_context_builder_params,
        concurrent_coroutines=32,
        response_type="multiple paragraphs",
    ) 的json_mode 改为False。 
    这个问题是你在构建图谱过程中的模型并不太支持json格式，返回值中存在如下错误：
    ’‘’
    好的，你需要的json内容如下：
    《一个json》
‘’‘

**Comment by xldistance** [comment]
> > global_search/serach.py里面的函数parse_search_response，parsed_elements = json.loads(search_response)["points"]这里运行出错
> 
> 修改setup_search_engines 下global_search_engine = GlobalSearch( llm=llm, context_builder=global_context_builder, token_encoder=token_encoder, max_data_tokens=12000, map_llm_params=map_llm_params, reduce_llm_params=reduce_llm_params, allow_general_knowledge=False, json_mode=True, context_builder_params=global_context_builder_params, concurrent_coroutines=32, response_type="multiple paragraphs", ) 的json_mode 改为False。 这个问题是你在构建图谱过程中的模型并不太支持json格式，返回值中存在如下错误： ’‘’ 好的，你需要的json内容如下： 《一个json》 ‘’‘

我换了模型internlm2.5:20b，现在global搜索不报错了

**Comment by shaoqing404** [comment]
> > > global_search/serach.py里面的函数parse_search_response，parsed_elements = json.loads(search_response)["points"]这里运行出错
> > 
> > 
> > 修改setup_search_engines 下global_search_engine = GlobalSearch( llm=llm, context_builder=global_context_builder, token_encoder=token_encoder, max_data_tokens=12000, map_llm_params=map_llm_params, reduce_llm_params=reduce_llm_params, allow_general_knowledge=False, json_mode=True, context_builder_params=global_context_builder_params, concurrent_coroutines=32, response_type="multiple paragraphs", ) 的json_mode 改为False。 这个问题是你在构建图谱过程中的模型并不太支持json格式，返回值中存在如下错误： ’‘’ 好的，你需要的json内容如下： 《一个json》 ‘’‘
> 
> 我换了模型internlm2.5:20b，现在global搜索不报错了

是的，和模型能力有关。我用的deepseek，也稳定
